export const POOLS = [
    '2300X',
    'ALLNODES_LIDO',
    'ANKR',
    'ANYBLOCKANALYTICS_LIDO',
    'ATTESTANTLIMITED_LIDO',
    'AVADO',
    'BINANCE',
    'BITCOINSUISSE',
    'BITFINEX',
    'BITFROST',
    'BITSTAMP',
    'BLOCKDAEMON_LIDO',
    'BLOCKSCAPE_LIDO',
    'BLOXSTAKING',
    'BRIDGETOWER_LIDO',
    'CELSIUS_NETWORK',
    'CERTUSONE_LIDO',
    'CHAINLAYER_LIDO',
    'CHAINSAFE_LIDO',
    'CHORUSONE_LIDO',
    'COINBASE',
    'CONSENSYSCODEFI_LIDO',
    'CREAM.FINANCE',
    'CRYPTOMANUFAKTUR_LIDO',
    'CRYPTOSTAKE.COM',
    'DANIELWANG.ETH',
    'DAPPNODE',
    'DSRV_LIDO',
    'ERIGONGFM',
    'EVERSTAKE_LIDO',
    'FIGMENT',
    'FIGMENT_LIDO',
    'GEMINI',
    'GHASH.ETH',
    'HASHQUARK_LIDO',
    'HUOBI',
    'INFSTONES',
    'INFSTONES_LIDO',
    'KILN_LIDO',
    'KRAKEN',
    'KUCOIN',
    'KUKISGLOBAL_LIDO',
    'LIGHTHOUSETEAM',
    'NEMORINO.ETH',
    'NETHERMIND_LIDO',
    'NIMBUSTEAM',
    'OKEX',
    'P2PORG_LIDO',
    'PIEDAO',
    'POGIBOY.ETH',
    'POLONIEX',
    'PRYSMATICLABS_LIDO',
    'PRYSMTEAM',
    'QUICKCASH',
    'ROCKETPOOL',
    'ROCKLOGICGMBH_LIDO',
    'ROCKX_LIDO',
    'SHAREDSTAKE',
    'SIGMAPRIME_LIDO',
    'SIMPLYSTAKING_LIDO',
    'STAKED.US',
    'STAKEFISH',
    'STAKEFISH_LIDO',
    'STAKEHOUND',
    'STAKELY_LIDO',
    'STAKEWISE',
    'STAKIN_LIDO',
    'STAKINGFACILITIES_LIDO',
    'TEKUTEAM',
    'TGERRING.ETH',
    'TOKENPOCKET',
    'VITALIK',
    'WANGDONG.ETH',
    'WAS.ETH',
    'WEXEXCHANGE_COPY',
    'WOLVERINE.ETH',
];

export const CLIENTS = [
    {
        name: 'Nimbus',
        description:
            "Nimbus is a client implementation for both Ethereum's consensus layer (eth2) and execution layer (eth1) that strives to be as lightweight as possible in terms of resources used. This allows it to perform well on embedded systems, embedded devices - including Raspberry Pis and mobile devices.",
        link: 'https://nimbus.team/',
        language: 'nim',
    },
    {
        name: 'Teku',
        description:
            'Teku is an open source Ethereum consensus client (previously called an Ethereum 2.0 client) written in Java. Teku contains a full beacon node implementation and a validator client for participating in proof of stake consensus. Written in Java and maintained by the same team behind Besu, Teku is equipped to bring staking services to businesses.',
        link: 'https://consensys.io/teku',
        language: 'java',
    },
    {
        name: 'Lighthouse',
        description:
            'Lighthouse is an Ethereum consensus client that connects to other Ethereum consensus clients to form a resilient and decentralized proof-of-stake blockchain. They implement the specification as defined in the ethereum/consensus-specs repository.',
        link: 'https://lighthouse.sigmaprime.io/',
        language: 'rust',
    },
    {
        name: 'Prysm',
        description:
            "Prysm is an Ethereum proof-of-stake client written in Go. You can use Prysm to participate in Ethereum's decentralized economy by running a node and, if you have 32 ETH to stake, a validator client.",
        link: 'https://docs.prylabs.network/docs/getting-started',
        language: 'go',
    },
    {
        name: 'Lodestar',
        description:
            "Lodestar is a consensus beacon node and validator client for the Ethereum blockchain. Lodestar's tools and libraries enable Ethereum protocol development for the JavaScript ecosystem.",
        link: 'https://lodestar.chainsafe.io/',
        language: 'javascript',
    },
];

export const ADDRESS_ZERO = '0x0000000000000000000000000000000000000000000000000000000000000000';
export const ADDRESS_ZERO_SHORT = '0x0000000000000000000000000000000000000000';
